HORIZON = 3
SEASON = 12

UNIT_SHIFT_MIN_RATIO = 50
UNIT_SHIFT_MIN_RUN = 3
OOS_MIN_DAYS = 1
INACTIVE_MONTHS = 6
MIN_OBS_SEASONAL_IMPUTE = 24

SHORT_HISTORY = 24
ADI_THRESHOLD = 1.32
SEASONAL_ACF_THRESHOLD = 0.33

MIN_TRAIN = 24
MIN_IMPROVEMENT = 0.05
BIAS_TOLERANCE = 0.05
BASELINE = "seasonal_naive"
